#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
values = []
def fib_less (&block)
	first = 1
	second = 1
	loop do
		yield second
		second = first + second
		first = second - first
	end
end

sum = 0
fib_less do |f|
	break if f > 4000000
	sum += f if f % 2 == 0
end
puts sum
